use serde::{Deserialize, Serialize};

/// Presentation theme selected by the host shell.
///
/// This is frame/chrome presentation only. Value formatting, conditional
/// formatting, and rendered value text remain engine-owned.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThemeMode {
    #[default]
    Light,
    Dark,
    HighContrast,
}

/// Skin-visible design tokens.
///
/// Skins should consume these through CSS custom properties (`var(--dtc-...)`)
/// and through this typed context when they need to branch on the active mode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThemeTokens {
    pub mode: ThemeMode,
    pub surface: String,
    pub surface_panel: String,
    pub surface_subtle: String,
    pub surface_muted: String,
    pub surface_input: String,
    pub text: String,
    pub text_muted: String,
    pub text_subtle: String,
    pub text_inverse: String,
    pub border: String,
    pub border_muted: String,
    pub border_strong: String,
    pub accent: String,
    pub accent_hover: String,
    pub accent_surface: String,
    pub accent_surface_muted: String,
    pub accent_border: String,
    pub accent_text: String,
    pub focus: String,
    pub success: String,
    pub success_surface: String,
    pub success_border: String,
    pub success_text: String,
    pub warning: String,
    pub warning_surface: String,
    pub warning_border: String,
    pub warning_text: String,
    pub danger: String,
    pub danger_surface: String,
    pub danger_border: String,
    pub danger_text: String,
    pub info_surface: String,
    pub info_border: String,
    pub info_text: String,
    pub kbd_surface: String,
    pub kbd_border: String,
    pub kbd_border_strong: String,
    pub kbd_text: String,
    pub shadow_soft: String,
    pub shadow_medium: String,
    pub shadow_inset: String,
}

impl ThemeTokens {
    #[must_use]
    pub fn light() -> Self {
        Self {
            mode: ThemeMode::Light,
            surface: "#ffffff".to_string(),
            surface_panel: "#fbfcfe".to_string(),
            surface_subtle: "#f6f8fb".to_string(),
            surface_muted: "#eef3f8".to_string(),
            surface_input: "#ffffff".to_string(),
            text: "#18212f".to_string(),
            text_muted: "#475569".to_string(),
            text_subtle: "#64748b".to_string(),
            text_inverse: "#ffffff".to_string(),
            border: "#d6dde7".to_string(),
            border_muted: "#e2e8ef".to_string(),
            border_strong: "#bdc9d8".to_string(),
            accent: "#245f9c".to_string(),
            accent_hover: "#1f4f83".to_string(),
            accent_surface: "#e5f1fb".to_string(),
            accent_surface_muted: "#eef4fa".to_string(),
            accent_border: "#8bb7dd".to_string(),
            accent_text: "#20537f".to_string(),
            focus: "#3c7fb1".to_string(),
            success: "#245c2a".to_string(),
            success_surface: "#eef8ef".to_string(),
            success_border: "#b9d5bb".to_string(),
            success_text: "#2f6b35".to_string(),
            warning: "#b7791f".to_string(),
            warning_surface: "#fff7e6".to_string(),
            warning_border: "#fed7aa".to_string(),
            warning_text: "#8a5a12".to_string(),
            danger: "#b91c1c".to_string(),
            danger_surface: "#fff7ed".to_string(),
            danger_border: "#fed7aa".to_string(),
            danger_text: "#9a3412".to_string(),
            info_surface: "#f0f9ff".to_string(),
            info_border: "#bae6fd".to_string(),
            info_text: "#075985".to_string(),
            kbd_surface: "#ffffff".to_string(),
            kbd_border: "#c4cfdc".to_string(),
            kbd_border_strong: "#aab7c7".to_string(),
            kbd_text: "#33485f".to_string(),
            shadow_soft: "rgba(15, 23, 42, 0.05)".to_string(),
            shadow_medium: "rgba(15, 23, 42, 0.16)".to_string(),
            shadow_inset: "rgba(15, 23, 42, 0.04)".to_string(),
        }
    }

    #[must_use]
    pub fn dark() -> Self {
        Self {
            mode: ThemeMode::Dark,
            surface: "#111827".to_string(),
            surface_panel: "#172033".to_string(),
            surface_subtle: "#0f172a".to_string(),
            surface_muted: "#1f2937".to_string(),
            surface_input: "#111827".to_string(),
            text: "#f8fafc".to_string(),
            text_muted: "#cbd5e1".to_string(),
            text_subtle: "#94a3b8".to_string(),
            text_inverse: "#0f172a".to_string(),
            border: "#334155".to_string(),
            border_muted: "#293548".to_string(),
            border_strong: "#475569".to_string(),
            accent: "#60a5fa".to_string(),
            accent_hover: "#93c5fd".to_string(),
            accent_surface: "#1e3a5f".to_string(),
            accent_surface_muted: "#172b45".to_string(),
            accent_border: "#2563eb".to_string(),
            accent_text: "#bfdbfe".to_string(),
            focus: "#93c5fd".to_string(),
            success: "#86efac".to_string(),
            success_surface: "#14301f".to_string(),
            success_border: "#22c55e".to_string(),
            success_text: "#bbf7d0".to_string(),
            warning: "#fbbf24".to_string(),
            warning_surface: "#3a2b0a".to_string(),
            warning_border: "#d97706".to_string(),
            warning_text: "#fde68a".to_string(),
            danger: "#fca5a5".to_string(),
            danger_surface: "#3a1111".to_string(),
            danger_border: "#ef4444".to_string(),
            danger_text: "#fecaca".to_string(),
            info_surface: "#082f49".to_string(),
            info_border: "#0284c7".to_string(),
            info_text: "#bae6fd".to_string(),
            kbd_surface: "#0f172a".to_string(),
            kbd_border: "#475569".to_string(),
            kbd_border_strong: "#64748b".to_string(),
            kbd_text: "#e2e8f0".to_string(),
            shadow_soft: "rgba(0, 0, 0, 0.24)".to_string(),
            shadow_medium: "rgba(0, 0, 0, 0.44)".to_string(),
            shadow_inset: "rgba(0, 0, 0, 0.28)".to_string(),
        }
    }

    #[must_use]
    pub fn high_contrast() -> Self {
        Self {
            mode: ThemeMode::HighContrast,
            surface: "#000000".to_string(),
            surface_panel: "#000000".to_string(),
            surface_subtle: "#000000".to_string(),
            surface_muted: "#111111".to_string(),
            surface_input: "#000000".to_string(),
            text: "#ffffff".to_string(),
            text_muted: "#ffffff".to_string(),
            text_subtle: "#ffffff".to_string(),
            text_inverse: "#000000".to_string(),
            border: "#ffffff".to_string(),
            border_muted: "#ffffff".to_string(),
            border_strong: "#ffffff".to_string(),
            accent: "#00ffff".to_string(),
            accent_hover: "#ffffff".to_string(),
            accent_surface: "#003333".to_string(),
            accent_surface_muted: "#001f1f".to_string(),
            accent_border: "#00ffff".to_string(),
            accent_text: "#00ffff".to_string(),
            focus: "#ffff00".to_string(),
            success: "#00ff00".to_string(),
            success_surface: "#003300".to_string(),
            success_border: "#00ff00".to_string(),
            success_text: "#00ff00".to_string(),
            warning: "#ffff00".to_string(),
            warning_surface: "#333300".to_string(),
            warning_border: "#ffff00".to_string(),
            warning_text: "#ffff00".to_string(),
            danger: "#ff6666".to_string(),
            danger_surface: "#330000".to_string(),
            danger_border: "#ff6666".to_string(),
            danger_text: "#ff6666".to_string(),
            info_surface: "#001f33".to_string(),
            info_border: "#00ffff".to_string(),
            info_text: "#00ffff".to_string(),
            kbd_surface: "#000000".to_string(),
            kbd_border: "#ffffff".to_string(),
            kbd_border_strong: "#ffffff".to_string(),
            kbd_text: "#ffffff".to_string(),
            shadow_soft: "none".to_string(),
            shadow_medium: "none".to_string(),
            shadow_inset: "none".to_string(),
        }
    }

    #[must_use]
    pub fn css_custom_properties(&self) -> String {
        let mode = match self.mode {
            ThemeMode::Light => "light",
            ThemeMode::Dark => "dark",
            ThemeMode::HighContrast => "high-contrast",
        };
        format!(
            concat!(
                "--dtc-theme-mode: '{}';",
                "--dtc-surface: {};",
                "--dtc-surface-panel: {};",
                "--dtc-surface-subtle: {};",
                "--dtc-surface-muted: {};",
                "--dtc-surface-input: {};",
                "--dtc-text: {};",
                "--dtc-text-muted: {};",
                "--dtc-text-subtle: {};",
                "--dtc-text-inverse: {};",
                "--dtc-border: {};",
                "--dtc-border-muted: {};",
                "--dtc-border-strong: {};",
                "--dtc-accent: {};",
                "--dtc-accent-hover: {};",
                "--dtc-accent-surface: {};",
                "--dtc-accent-surface-muted: {};",
                "--dtc-accent-border: {};",
                "--dtc-accent-text: {};",
                "--dtc-focus: {};",
                "--dtc-success: {};",
                "--dtc-success-surface: {};",
                "--dtc-success-border: {};",
                "--dtc-success-text: {};",
                "--dtc-warning: {};",
                "--dtc-warning-surface: {};",
                "--dtc-warning-border: {};",
                "--dtc-warning-text: {};",
                "--dtc-danger: {};",
                "--dtc-danger-surface: {};",
                "--dtc-danger-border: {};",
                "--dtc-danger-text: {};",
                "--dtc-info-surface: {};",
                "--dtc-info-border: {};",
                "--dtc-info-text: {};",
                "--dtc-kbd-surface: {};",
                "--dtc-kbd-border: {};",
                "--dtc-kbd-border-strong: {};",
                "--dtc-kbd-text: {};",
                "--dtc-shadow-soft: {};",
                "--dtc-shadow-medium: {};",
                "--dtc-shadow-inset: {};",
            ),
            mode,
            self.surface,
            self.surface_panel,
            self.surface_subtle,
            self.surface_muted,
            self.surface_input,
            self.text,
            self.text_muted,
            self.text_subtle,
            self.text_inverse,
            self.border,
            self.border_muted,
            self.border_strong,
            self.accent,
            self.accent_hover,
            self.accent_surface,
            self.accent_surface_muted,
            self.accent_border,
            self.accent_text,
            self.focus,
            self.success,
            self.success_surface,
            self.success_border,
            self.success_text,
            self.warning,
            self.warning_surface,
            self.warning_border,
            self.warning_text,
            self.danger,
            self.danger_surface,
            self.danger_border,
            self.danger_text,
            self.info_surface,
            self.info_border,
            self.info_text,
            self.kbd_surface,
            self.kbd_border,
            self.kbd_border_strong,
            self.kbd_text,
            self.shadow_soft,
            self.shadow_medium,
            self.shadow_inset,
        )
    }

    #[must_use]
    pub fn css_rule(&self, selector: &str) -> String {
        format!("{} {{{}}}", selector, self.css_custom_properties())
    }
}
